title: The We Can Zone
author: sguthals
email: sarah@thewecan.zone
description: > # this means to ignore newlines until "baseurl:"
  Welcome! 
# social links
twitter_username: sarahguthals
github_username:  sguthals

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-leap-day
